# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

desc "Create on Developer Portal and App Store Connect"
lane :create_app do
  create_app_online # produce
end

default_platform(:ios)
platform :ios do
  desc "Sync signing"
  lane :signing do
    sync_code_signing # match
  end

  desc "Build buinary"
  lane :build do
#    increment_build_number(xcodeproj: "TestFastlane.xcodeproj")
    build_ios_app
  end
  desc "Push a new release build to the App Store"
  lane :release do
#    increment_build_number(xcodeproj: "TestFastlane.xcodeproj")
#    build_app(scheme: "TestFastlane")
#    upload_to_app_store
  end
end
